// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoygvfDwEKZVK_YL6MP6YDNddi7waRY8Q',
    appId: '1:17824399971:web:ee14646410d92745486e56',
    messagingSenderId: '17824399971',
    projectId: 'ecotrack-hackathon',
    authDomain: 'ecotrack-hackathon.firebaseapp.com',
    storageBucket: 'ecotrack-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM4ItwGbYaM3yJ54VM068lnZIR0Jzp1SY',
    appId: '1:17824399971:android:53d7549360b9ee17486e56',
    messagingSenderId: '17824399971',
    projectId: 'ecotrack-hackathon',
    storageBucket: 'ecotrack-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyNrpUAAFNzLhjUJ3mm9l4ZQVAZ4R0ZRE',
    appId: '1:17824399971:ios:f1dce8a5bbf0f8e0486e56',
    messagingSenderId: '17824399971',
    projectId: 'ecotrack-hackathon',
    storageBucket: 'ecotrack-hackathon.firebasestorage.app',
    iosClientId: '17824399971-14lf2kreb8lk5djdhd4ekops9jvrhviv.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyNrpUAAFNzLhjUJ3mm9l4ZQVAZ4R0ZRE',
    appId: '1:17824399971:ios:f1dce8a5bbf0f8e0486e56',
    messagingSenderId: '17824399971',
    projectId: 'ecotrack-hackathon',
    storageBucket: 'ecotrack-hackathon.firebasestorage.app',
    iosClientId: '17824399971-14lf2kreb8lk5djdhd4ekops9jvrhviv.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoygvfDwEKZVK_YL6MP6YDNddi7waRY8Q',
    appId: '1:17824399971:web:61d7f1553c7a56d0486e56',
    messagingSenderId: '17824399971',
    projectId: 'ecotrack-hackathon',
    authDomain: 'ecotrack-hackathon.firebaseapp.com',
    storageBucket: 'ecotrack-hackathon.firebasestorage.app',
  );
}
